# Site settings
title: Web Developer from Weblime
email: al.ulianov@gmail.com
description: Фронтенд и веб-разработка
url: "donrai.github.io"
twitter_username: al_ulianov
github_username:  DonRai
facebook_username:  100001768056957

# Build settings
# markdown: kramdown
markdown: kramdown
permalink: /:title

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "DonRai"
      author_name: "Алексей Ульянов"
      layout: "post"
      type: article
      comments: true

exclude:
  - node_modules
  - bower_components
  - gulpfile.js
  - bower.json
  - styles
  - scsslint.yml
  - package.json

gems:
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num"
